# Write a program to input eight numbers from the user and display all the unique number(once.)

a = set()
b = int(input("Put number: "))
a.add(int(b))
b = int(input("Put number: "))
a.add(int(b))
b = int(input("Put number: "))
a.add(int(b))
b = int(input("Put number: "))
a.add(int(b))
b = int(input("Put number: "))
a.add(int(b))
b = int(input("Put number: "))
a.add(int(b))
b = int(input("Put number: "))
a.add(int(b))
b = int(input("Put number: "))
a.add(int(b))
print(a)