d = {}
name = input("Enter name: ")
lang = input("Enter Fav language: ")
d.update({name:lang})
name = input("Enter name: ")
lang = input("Enter Fav language: ")
d.update({name:lang})
name = input("Enter name: ")
lang = input("Enter Fav language: ")
d.update({name:lang})
name = input("Enter name: ")
lang = input("Enter Fav language: ")
d.update({name:lang})
print(d)